version: '3'
services:
  download_zookeeper_1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  download_kafka_1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.88.14
      KAFKA_ZOOKEEPER_CONNECT: download_zookeeper_1:2181
